import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Header } from "./components/shared/Header";
import { Footer } from "./components/shared/Footer";
import "../sass/global.sass";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bsg Pay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
